### ISSUE TITLE
animationDuration set problem

### ISSUE THREAD

**Issue by xevser** [andr3a88/ASProgressHud#3]
Hi andr3a88
Thank you for this great repository. I have an issue on animationDuration on property. We set animationDuration on init, but the value can not be changed. It takes the default hardcoded value. 
Please check. 
Also it will be very pleased if we can change the cornerRadius value from outside.

Thank you.
Have a nice day :)
Kevser

**Comment by andr3a88** [comment]
Hi, I will check as soon as possible!

Thank you

**Comment by andr3a88** [comment]
Issue fixed, checkout the version `1.0.3`
